version: "3.2"
services:
  php-7-fpm:
    container_name: php-7-fpm
    image: cloudyne.azurecr.io/php:7-fpm
    build:
      context: .
      dockerfile: base.Dockerfile
      args:
        BUILD_ENV: debug
        ALPINE_VERSION: 3.17
        PHP_VERSION: 7
        DEBUG_PACKAGES: nano bash net-tools wget
  
  php-8-fpm:
    container_name: php-8-fpm
    image: cloudyne.azurecr.io/php:8-fpm
    build:
      context: .
      dockerfile: base.Dockerfile
      args:
        BUILD_ENV: debug
        ALPINE_VERSION: 3.17
        PHP_VERSION: 8
        DEBUG_PACKAGES: nano bash net-tools wget

  php-fpm7-debug:
    container_name: phpdebug7-fpm
    image: phpdebug:7-fpm
    build:
      context: .
      dockerfile: base.Dockerfile
      args:
        BUILD_ENV: debug
        ALPINE_VERSION: 3.17
        PHP_VERSION: 7
        DEBUG_PACKAGES: nano bash net-tools wget
  
  php-fpm8-debug:
    container_name: phpdebug8-fpm
    image: phpdebug:8-fpm
    build:
      context: .
      dockerfile: base.Dockerfile
      args:
        BUILD_ENV: debug
        ALPINE_VERSION: 3.17
        PHP_VERSION: 8
        DEBUG_PACKAGES: nano bash net-tools wget
  
  php-7-nginx:
    container_name: php-7-nginx
    image: cloudyne.azurecr.io/php:7-nginx
    build:
      context: .
      dockerfile: nginx.Dockerfile
      args:
        BUILD_ENV: debug
        ALPINE_VERSION: 3.17
        PHP_VERSION: 7
        DEBUG_PACKAGES: nano bash net-tools wget
  
  php-8-nginx:
    container_name: php-8-nginx
    image: cloudyne.azurecr.io/php:8-nginx
    build:
      context: .
      dockerfile: nginx.Dockerfile
      args:
        BUILD_ENV: debug
        ALPINE_VERSION: 3.17
        PHP_VERSION: 8
        DEBUG_PACKAGES: nano bash net-tools wget

  php-nginx7-debug:
    container_name: phpdebug7-nginx
    image: phpdebug:7-nginx
    build:
      context: .
      dockerfile: nginx.Dockerfile
      args:
        BUILD_ENV: debug
        ALPINE_VERSION: 3.17
        PHP_VERSION: 7
        DEBUG_PACKAGES: nano bash net-tools wget
  
  php-nginx8-debug:
    container_name: phpdebug8-nginx
    image: phpdebug:8-nginx
    build:
      context: .
      dockerfile: nginx.Dockerfile
      args:
        BUILD_ENV: debug
        ALPINE_VERSION: 3.17
        PHP_VERSION: 8
        DEBUG_PACKAGES: nano bash net-tools wget
  
  bed:
    container_name: bed
    image: cloudyne.azurecr.io/php:8-bedrock
    build:
      context: .
      dockerfile: bedrock.Dockerfile
      args:
        PHP_VERSION: 8
        SRC_IMAGE_TYPE: fpm
    ports:
      - 8080:8080