version: "3.2"
services:

  # PHP-FPM Only
  php8:
    container_name: php8
    image: cloudyne.azurecr.io/php:8
    build:
      context: .
      dockerfile: base.Dockerfile
      args:
        ALPINE_VERSION: 3.17
        PHP_VERSION: 8
    ports:
      - 8123:8123

  # PHP-FPM and Nginx
  php8-nginx:
    container_name: php8-nginx
    image: cloudyne.azurecr.io/php:8-nginx
    build:
      context: .
      dockerfile: nginx.Dockerfile
      args:
        ALPINE_VERSION: 3.17
        PHP_VERSION: 8
    ports:
      - 8080:8080
  
  # Roots Bedrock
  php8-bedrock:
    container_name: php8-bedrock
    image: cloudyne.azurecr.io/php:8-bedrock
    build:
      context: .
      dockerfile: bedrock.Dockerfile
      args:
        PHP_VERSION: 8
        SRC_IMAGE_TYPE: -nginx
    ports:
      - 8080:8080
  
  # Codeigniter4
  php8-codeigniter:
    container_name: php8-codeigniter
    image: cloudyne.azurecr.io/php:8-codeigniter
    build:
      context: .
      dockerfile: codeigniter.Dockerfile
      args:
        PHP_VERSION: 8
        SRC_IMAGE_TYPE: -nginx
    ports:
      - 8080:8080
  
  # Codeigniter4
  php8-phpmyadmin:
    container_name: php8-phpmyadmin
    image: cloudyne.azurecr.io/php:8-phpmyadmin
    build:
      context: .
      dockerfile: phpmyadmin.Dockerfile
      args:
        PHP_VERSION: 8
        SRC_IMAGE_TYPE: -nginx
    ports:
      - 8080:8080
  
  # Init Container
  php8-init:
    container_name: php8-init
    image: cloudyne.azurecr.io/php:8-init
    build:
      context: .
      dockerfile: init.Dockerfile
      args:
        PHP_VERSION: 8